name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        # 0. Checkout the code from the repo
        # 1. React uygulaması için gerekli dependency'ler yüklenecek.
        # 2. Otomatize edilmiş testler çalıştırılacak.
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Show Folder Names
              run: ls
