name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build-status: ${{ steps.build-step.outputs.status }}

    steps:
      - name: Print 'GITHUB_OUTPUT' Path
        run: echo "$GITHUB_OUTPUT"

      - name: Build
        id: build-step
        run: |
          echo "$GITHUB_OUTPUT"
          echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
          echo "first_output=first_value" >> "$GITHUB_OUTPUT"
          echo "second_output=second_value" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploying"

      - name: Print Outputs
        run: |
          echo "Output 1: ${{ needs.build.outputs.output1 }}"
