name: 16 - Working with Environments
run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      my_env_value: ${{ vars.MY_ENV_VALUE || 'No Environment Value Defined' }}
    steps:
      - name: Echo Data
        run: |
          echo "Environment Variable: ${{ env.my_env_value }}"
