name: 16 - Working with Environments
run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
jobs:
  echo-custom:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      my_env_value: ${{ vars.MY_ENV_VALUE || 'No Environment Value Defined' }}
    steps:
      - name: Echo Data
        run: |
          echo "Environment Variable: ${{ env.my_env_value }}"

  deploy-staging:
    needs: echo-custom
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Echo Data
        run: echo "Deploying to Staging environment"

  e2e-test:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: E2E Tests
        run: echo "Running E2e Tests"

  deploy-prod-backend-1:
    needs: e2e-test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Echo Data
        run: echo "Deploying to Prod Backend 1 at Prod environment"

  deploy-prod-backend-2:
    needs: e2e-test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Echo Data
        run: echo "Deploying to Prod Backend 1 at Prod environment"

  deploy-prod-frontend:
    needs: e2e-test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Echo Data
        run: echo "Deploying to Prod Frontend at Prod environment"
